# Generated by Django 2.2.6 on 2022-02-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220203_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='uid',
        ),
    ]
