# Generated by Django 2.2.6 on 2022-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220204_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='uid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
